language: ruby
os: linux
dist: xenial
cache:
  directories:
    - vendor/bundle
    - node_modules
addons:
  firefox: latest
services:
  - mysql
  - xvfb
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('1234') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p1234
  - sudo service mysql restart
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq yarn
  - gem install bundler:2.0.2
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -zxvf geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin/
install:
  - bundle install --path vendor/bundle
  - yarn install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use $TRAVIS_NODE_VERSION
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    recipients:
      - drabkirn@cdadityang.xyz
    on_success: never
    on_failure: always
branches:
  only: 
    - master
