test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  appza_secret:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  appza_secret:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  appza_secret: