test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  newsletter_list_id:
  newsletter_client_id:
  newsletter_client_secret:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  newsletter_list_id:
  newsletter_client_id:
  newsletter_client_secret:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  newsletter_list_id:
  newsletter_client_id:
  newsletter_client_secret: