test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  newsletter_list_id:
  newsletter_api_key:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  newsletter_list_id:
  newsletter_api_key:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  newsletter_list_id:
  newsletter_api_key: