test:
  db_hostname:
  db_username:
  db_password:
  db_name:
  capybara_screenshots_path:
  appza_secret:
  sitemap_host:


development:
  db_hostname:
  db_username:
  db_password:
  db_name:
  appza_secret:
  sitemap_host:


production:
  db_hostname:
  db_username:
  db_password:
  db_name:
  appza_secret:
  sitemap_host: